# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Subspider
tagline:          ''
description:      'Just a blog from a Software Developer sharing thougths'
url:              http://subspider.github.io

author:
  name:           'Pedro Santos'
  url:            https://twitter.com/pedroAGSantos
gems:             [jekyll-paginate]
paginate:         5
paginate_path:    "page:num"

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/subspider/subspider.github.io
