# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Pedro Santos
email: pedroalbertogodinho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Sofware Developer most of my career I focused on mobile platforms Android and iOS.
  Love photography, sports and traveling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://subspidergithub.io" # the base hostname & protocol for your site
twitter_username: PedroAGSantos
github_username:  subspider

# Build settings
markdown: kramdown
